#!/bin/bash

read -r -p "Are You Sure? [y/n] " input
 
case $input in
      [yY][eE][sS]|[yY])
        git branch | grep -ve "[main|master]$" | xargs git branch -D
            ;;
      [nN][oO]|[nN])
            exit 0
            ;;
      *)
            exit 1
            ;;
esac
