#!/bin/bash


read -r -p "Are You Sure? [y/N] " input
 
case $input in
  [yY][eE][sS]|[yY])
    git branch | grep -vE "(?:master)|(?:main)$" | xargs git branch -D
    ;;
  [nN][oO]|[nN])
    exit 0
    ;;
  *)
    exit 1
    ;;
esac
